spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Boluwatife2006}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI:https://ngcloak-production.up.railway.app/realms/ecommerce}
        registration:
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID:ecommerce-app}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:xLl1RuQ087mnGzue5AroeW6QGsf7tx4Z}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
            redirect-uri: ${APP_BASE_URL:http://localhost:8081}/login/oauth2/code/keycloak
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

app:
  upload-dir: ${UPLOAD_DIR:./uploads/products}
  base-url: ${APP_BASE_URL:http://localhost:8081}

paystack:
  secret-key: ${PAYSTACK_SECRET_KEY:sk_test_100deea18599e2e1f31d5d8397e1f46602fdf1ea}

springdoc:
  pathsToMatch: /api/**

keycloak:
  admin:
    server-url: ${KEYCLOAK_SERVER_URL:https://ngcloak-production.up.railway.app}
    realm: ${KEYCLOAK_REALM:ecommerce}
    admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

sms:
  termii:
    api-key: ${TERMII_API_KEY:}
    sender-id: ${TERMII_SENDER_ID:NaijaMart}
  africastalking:
    api-key: ${AT_API_KEY:}
    username: ${AT_USERNAME:sandbox}
    sender-id: ${AT_SENDER_ID:}
  twilio:
    account-sid: ${TWILIO_ACCOUNT_SID:}
    auth-token: ${TWILIO_AUTH_TOKEN:}
    from-number: ${TWILIO_FROM_NUMBER:}
